#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    
    #line 2 "..\..\Pages\ErrorPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 3 "..\..\Pages\ErrorPage.cshtml"
    using Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ErrorPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("<!DOCTYPE html>\r\n\r\n<html lang=\"ru\">\r\n<head>\r\n    <title>Error - HangFire</title>\r" +
"\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" content=\"width=device-w" +
"idth, initial-scale=1.0\">\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 12 "..\..\Pages\ErrorPage.cshtml"
                            Write(Request.LinkTo("/css/styles.css"));

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n</head>\r\n<body>\r\n    <div class=\"container\">\r\n        <div class=\"jumbotron" +
"\" style=\"margin-top: 40px;\">\r\n\r\n            <h1>HangFire <small>An exception occ" +
"urred</small></h1>\r\n            <p class=\"lead\">");


            
            #line 19 "..\..\Pages\ErrorPage.cshtml"
                       Write(Exception.Message);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n\r\n            <pre>");


            
            #line 21 "..\..\Pages\ErrorPage.cshtml"
            Write(HtmlHelper.MarkupStackTrace(Exception.ToString()));

            
            #line default
            #line hidden
WriteLiteral("</pre>\r\n        </div>\r\n    </div>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
