#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web
{
    
    #line 2 "..\..\DashboardPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\DashboardPage.cshtml"
    using System.Globalization;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class DashboardPage : WebTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("              \r\n");


            
            #line 6 "..\..\DashboardPage.cshtml"
  
    Layout = new LayoutPage()
        {
            Context = Context,
            Title = "Dashboard"
        };


            
            #line default
            #line hidden
WriteLiteral("\r\n<div id=\"realtime\"></div>");


        }
    }
}
#pragma warning restore 1591
