codecov:
  notify:
    require_ci_to_pass: true
    threshold: 1%
comment:
  behavior: default
  layout: header,tree
  require_changes: true
coverage:
  precision: 2
  range:
  - 70.0
  - 100.0
  round: down
  status:
    changes: false
    patch: false
    project: true
parsers:
  gcov:
    branch_detection:
      conditional: true
      loop: true
      macro: false
      method: false
  javascript:
    enable_partials: false
