#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18047
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\DashboardPage.cshtml"
    using HangFire.Web.Pages;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Pages\DashboardPage.cshtml"
    using ServiceStack.Text;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "1.5.3.0")]
    internal partial class DashboardPage : WebTemplateBase
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




WriteLiteral("              \r\n");


            
            #line 6 "..\..\Pages\DashboardPage.cshtml"
  
    Layout = new LayoutPage
        {
            Context = Context,
            Title = "Dashboard"
        };


            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>Realtime graph</h3>\r\n<div id=\"realtime\"></div>\r\n\r\n");


            
            #line 17 "..\..\Pages\DashboardPage.cshtml"
  
    // TODO: get rid of this. We have no right to change the library globals.
    JsConfig.DateHandler = JsonDateHandler.ISO8601;


            
            #line default
            #line hidden
WriteLiteral("\r\n<h3>History graph</h3>\r\n<div id=\"history\" \r\n     data-succeeded=\"");


            
            #line 24 "..\..\Pages\DashboardPage.cshtml"
                Write(JsonSerializer.SerializeToString(HangFireApi.HourlySucceededJobs()));

            
            #line default
            #line hidden
WriteLiteral("\" \r\n     data-failed=\"");


            
            #line 25 "..\..\Pages\DashboardPage.cshtml"
             Write(JsonSerializer.SerializeToString(HangFireApi.HourlyFailedJobs()));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n</div>");


        }
    }
}
#pragma warning restore 1591
