#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    
    #line 2 "..\..\Pages\JobDetailsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Pages\JobDetailsPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Pages\JobDetailsPage.cshtml"
    using Common;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Pages\JobDetailsPage.cshtml"
    using Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobDetailsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Pages\JobDetailsPage.cshtml"
  
    Layout = new LayoutPage { Title = "Job", Subtitle = JobId.ToString() };
    var job = JobStorage.JobDetails(JobId.ToString());


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 12 "..\..\Pages\JobDetailsPage.cshtml"
 if (job == null)
{

            
            #line default
            #line hidden
WriteLiteral("    ");

WriteLiteral(" The job with id \'");


            
            #line 14 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(JobId);

            
            #line default
            #line hidden
WriteLiteral("\' was expired or was not existed on the server.\r\n");


            
            #line 15 "..\..\Pages\JobDetailsPage.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral("    <h3>\r\n        <span class=\"label label-default\" style=\"");


            
            #line 19 "..\..\Pages\JobDetailsPage.cshtml"
                                             Write(JobHistoryRenderer.ForegroundStateColors.ContainsKey(job.State) ? String.Format("background-color: {0};", JobHistoryRenderer.ForegroundStateColors[job.State]) : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            ");


            
            #line 20 "..\..\Pages\JobDetailsPage.cshtml"
       Write(job.State);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n        <small>\r\n            ");


            
            #line 22 "..\..\Pages\JobDetailsPage.cshtml"
       Write(HtmlHelper.JobType(job.Method));

            
            #line default
            #line hidden
WriteLiteral("\r\n        </small>\r\n    </h3>\r\n");


            
            #line 25 "..\..\Pages\JobDetailsPage.cshtml"
    
    if (job.OldFormatArguments != null && job.OldFormatArguments.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("    <table class=\"table table-condensed table-bordered table-striped\">\r\n        <" +
"thead>\r\n            <tr>\r\n                <th class=\"width-200\">Name</th>\r\n     " +
"           <th>Value</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r" +
"\n");


            
            #line 36 "..\..\Pages\JobDetailsPage.cshtml"
             foreach (var arg in job.OldFormatArguments)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 39 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(arg.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td><pre class=\"pre-args\">");


            
            #line 40 "..\..\Pages\JobDetailsPage.cshtml"
                                         Write(arg.Value);

            
            #line default
            #line hidden
WriteLiteral("</pre></td>\r\n                </tr>\r\n");


            
            #line 42 "..\..\Pages\JobDetailsPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 45 "..\..\Pages\JobDetailsPage.cshtml"
    }

    if (job.Properties.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("    <h3>Properties</h3>\r\n");



WriteLiteral("    <table class=\"table table-condensed table-bordered table-striped\">\r\n        <" +
"thead>\r\n            <tr>\r\n                <th class=\"width-200\">Name</th>\r\n     " +
"           <th>Value</th>\r\n            </tr>\r\n        </thead>\r\n        <tbody>\r" +
"\n");


            
            #line 58 "..\..\Pages\JobDetailsPage.cshtml"
             foreach (var property in job.Properties)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 61 "..\..\Pages\JobDetailsPage.cshtml"
                   Write(property.Key);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                    <td><code>");


            
            #line 62 "..\..\Pages\JobDetailsPage.cshtml"
                         Write(property.Value);

            
            #line default
            #line hidden
WriteLiteral("</code></td>\r\n                </tr>\r\n");


            
            #line 64 "..\..\Pages\JobDetailsPage.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 67 "..\..\Pages\JobDetailsPage.cshtml"
    }

    if (job.History.Count > 0)
    {

            
            #line default
            #line hidden
WriteLiteral("    <h3>History</h3>\r\n");


            
            #line 72 "..\..\Pages\JobDetailsPage.cshtml"
        foreach (var entry in job.History)
        {

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"job-history\">\r\n        <div class=\"job-history-heading\" style=\"");


            
            #line 75 "..\..\Pages\JobDetailsPage.cshtml"
                                            Write(JobHistoryRenderer.BackgroundStateColors.ContainsKey(entry["State"]) ? String.Format("background-color: {0};", JobHistoryRenderer.BackgroundStateColors[entry["State"]]) : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n            <span class=\"pull-right\" data-moment=\"");


            
            #line 76 "..\..\Pages\JobDetailsPage.cshtml"
                                             Write(entry["CreatedAt"]);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 76 "..\..\Pages\JobDetailsPage.cshtml"
                                                                  Write(JobHelper.FromStringTimestamp(entry["CreatedAt"]));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n            <h4 class=\"job-history-title\">\r\n                ");


            
            #line 78 "..\..\Pages\JobDetailsPage.cshtml"
           Write(entry["State"]);

            
            #line default
            #line hidden
WriteLiteral("\r\n\r\n");


            
            #line 80 "..\..\Pages\JobDetailsPage.cshtml"
                 if (!String.IsNullOrEmpty(entry["Reason"]))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <small>");


            
            #line 82 "..\..\Pages\JobDetailsPage.cshtml"
                      Write(entry["Reason"]);

            
            #line default
            #line hidden
WriteLiteral("</small>\r\n");


            
            #line 83 "..\..\Pages\JobDetailsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </h4>\r\n        </div>\r\n\r\n");


            
            #line 87 "..\..\Pages\JobDetailsPage.cshtml"
         if (JobHistoryRenderer.Exists(entry["State"]))
        {
            var rendered = JobHistoryRenderer.Render(entry["State"], entry);
            if (rendered != null)
            {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"job-history-body\">\r\n                ");


            
            #line 93 "..\..\Pages\JobDetailsPage.cshtml"
           Write(rendered);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 95 "..\..\Pages\JobDetailsPage.cshtml"
            }
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"job-history-body\">\r\n                <dl class=\"dl-horizon" +
"tal\">\r\n");


            
            #line 101 "..\..\Pages\JobDetailsPage.cshtml"
                     foreach (var item in entry.Where(x => x.Key != "State" && x.Key != "Date" && x.Key != "Reason"))
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <dt>");


            
            #line 103 "..\..\Pages\JobDetailsPage.cshtml"
                       Write(item.Key);

            
            #line default
            #line hidden
WriteLiteral(":</dt>\r\n");



WriteLiteral("                        <dd>");


            
            #line 104 "..\..\Pages\JobDetailsPage.cshtml"
                       Write(item.Value);

            
            #line default
            #line hidden
WriteLiteral("</dd>\r\n");


            
            #line 105 "..\..\Pages\JobDetailsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </dl>\r\n            </div>\r\n");


            
            #line 108 "..\..\Pages\JobDetailsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n");


            
            #line 110 "..\..\Pages\JobDetailsPage.cshtml"
        }
    }
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
