#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    
    #line 2 "..\..\Pages\LayoutPage.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Pages\LayoutPage.cshtml"
    using System.Diagnostics;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Pages\LayoutPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class LayoutPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");





WriteLiteral("<!DOCTYPE html>\r\n\r\n<html lang=\"ru\">\r\n<head>\r\n    <title>");


            
            #line 10 "..\..\Pages\LayoutPage.cshtml"
      Write(Title);

            
            #line default
            #line hidden
WriteLiteral(" - HangFire</title>\r\n    <meta charset=\"utf-8\" />\r\n    <meta name=\"viewport\" cont" +
"ent=\"width=device-width, initial-scale=1.0\">\r\n    <link rel=\"stylesheet\" href=\"");


            
            #line 13 "..\..\Pages\LayoutPage.cshtml"
                            Write(Request.LinkTo("/css/styles.css"));

            
            #line default
            #line hidden
WriteLiteral(@""" />
</head>
<body>
    <!-- Wrap all page content here -->
    <div id=""wrap"">

        <!-- Fixed navbar -->
        <div class=""navbar navbar-default navbar-fixed-top"">
            <div class=""container"">
                <div class=""navbar-header"">
                    <button type=""button"" class=""navbar-toggle"" data-toggle=""collapse"" data-target="".navbar-collapse"">
                        <span class=""icon-bar""></span>
                        <span class=""icon-bar""></span>
                        <span class=""icon-bar""></span>
                    </button>
                    <a class=""navbar-brand"" href=""");


            
            #line 28 "..\..\Pages\LayoutPage.cshtml"
                                             Write(Request.LinkTo("/"));

            
            #line default
            #line hidden
WriteLiteral("\">HangFire Monitor</a>\r\n                </div>\r\n                <div class=\"colla" +
"pse navbar-collapse\">\r\n                    <ul class=\"nav navbar-nav\">\r\n        " +
"                <li class=\"");


            
            #line 32 "..\..\Pages\LayoutPage.cshtml"
                               Write(Request.PathInfo.Equals("/") || Request.PathInfo.Equals("") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <a href=\"");


            
            #line 33 "..\..\Pages\LayoutPage.cshtml"
                                Write(Request.LinkTo("/"));

            
            #line default
            #line hidden
WriteLiteral("\">Dashboard</a>\r\n                        </li>\r\n                        <li class" +
"=\"");


            
            #line 35 "..\..\Pages\LayoutPage.cshtml"
                               Write(Request.PathInfo.Equals("/servers") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <a href=\"");


            
            #line 36 "..\..\Pages\LayoutPage.cshtml"
                                 Write(Request.LinkTo("/servers"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                Servers\r\n                                <spa" +
"n class=\"badge\">");


            
            #line 38 "..\..\Pages\LayoutPage.cshtml"
                                               Write(JobStorage.Servers().Count());

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                            </a>                            \r\n          " +
"              </li>\r\n                        <li class=\"");


            
            #line 41 "..\..\Pages\LayoutPage.cshtml"
                               Write(Request.PathInfo.Equals("/queues") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                            <a href=\"");


            
            #line 42 "..\..\Pages\LayoutPage.cshtml"
                                Write(Request.LinkTo("/queues"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                Queues\r\n                                <span" +
" class=\"badge\">");


            
            #line 44 "..\..\Pages\LayoutPage.cshtml"
                                               Write(JobStorage.Queues().Count());

            
            #line default
            #line hidden
WriteLiteral(@"</span>
                            </a>
                        </li>
                    </ul>
                    <ul class=""nav navbar-nav navbar-right"">
                        <li>
                            <a href=""/"">Back to site</a>
                        </li>
                    </ul>
                </div>
                <!--/.nav-collapse -->
            </div>
        </div>

        <!-- Begin page content -->

        <div class=""container"">
            <div class=""col-md-3"">
                <div id=""stats"" class=""list-group"" data-refresh-url=""");


            
            #line 62 "..\..\Pages\LayoutPage.cshtml"
                                                                Write(Request.LinkTo("/stats"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                    <a class=\"list-group-item ");


            
            #line 63 "..\..\Pages\LayoutPage.cshtml"
                                          Write(Request.PathInfo.Equals("/enqueued") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                       href=\"");


            
            #line 64 "..\..\Pages\LayoutPage.cshtml"
                        Write(Request.LinkTo("/enqueued"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span id=\"stats-enqueued\" class=\"label label-default " +
"pull-right\">\r\n                            ");


            
            #line 66 "..\..\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0:n0}", JobStorage.EnqueuedCount()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        Enqueued\r\n            " +
"        </a>\r\n                    <a class=\"list-group-item ");


            
            #line 70 "..\..\Pages\LayoutPage.cshtml"
                                          Write(Request.PathInfo.Equals("/schedule") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                       href=\"");


            
            #line 71 "..\..\Pages\LayoutPage.cshtml"
                        Write(Request.LinkTo("/schedule"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span id=\"stats-scheduled\" class=\"label label-info pu" +
"ll-right\">\r\n                            ");


            
            #line 73 "..\..\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0:n0}", JobStorage.ScheduledCount()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        Scheduled\r\n           " +
"         </a>\r\n                    <a class=\"list-group-item ");


            
            #line 77 "..\..\Pages\LayoutPage.cshtml"
                                          Write(Request.PathInfo.Equals("/processing") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                       href=\"");


            
            #line 78 "..\..\Pages\LayoutPage.cshtml"
                        Write(Request.LinkTo("/processing"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span id=\"stats-workers\" class=\"label label-warning p" +
"ull-right\">\r\n                            ");


            
            #line 80 "..\..\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0:n0}", JobStorage.ProcessingJobs().Count()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        Processing\r\n          " +
"          </a>\r\n                    <a class=\"list-group-item ");


            
            #line 84 "..\..\Pages\LayoutPage.cshtml"
                                          Write(Request.PathInfo.Equals("/succeeded") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                       href=\"");


            
            #line 85 "..\..\Pages\LayoutPage.cshtml"
                        Write(Request.LinkTo("/succeeded"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span id=\"stats-succeeded\" class=\"label label-success" +
" pull-right\">\r\n                            ");


            
            #line 87 "..\..\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0:n0}", JobStorage.SucceededCount()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        Succeeded\r\n           " +
"         </a>\r\n                    <a class=\"list-group-item ");


            
            #line 91 "..\..\Pages\LayoutPage.cshtml"
                                          Write(Request.PathInfo.Equals("/failed") ? "active" : null);

            
            #line default
            #line hidden
WriteLiteral("\" \r\n                       href=\"");


            
            #line 92 "..\..\Pages\LayoutPage.cshtml"
                        Write(Request.LinkTo("/failed"));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <span id=\"stats-failed\" class=\"label label-danger pul" +
"l-right\">\r\n                            ");


            
            #line 94 "..\..\Pages\LayoutPage.cshtml"
                       Write(String.Format("{0:n0}", JobStorage.FailedCount()));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </span>\r\n                        Failed\r\n              " +
"      </a>\r\n                </div>\r\n            </div>\r\n            <div class=\"" +
"col-md-9\">\r\n                <h1 class=\"page-header\">");


            
            #line 101 "..\..\Pages\LayoutPage.cshtml"
                                   Write(Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n                ");


            
            #line 102 "..\..\Pages\LayoutPage.cshtml"
           Write(RenderBody());

            
            #line default
            #line hidden
WriteLiteral(@"
            </div>
        </div>
    </div>

    <div id=""footer"">
        <div class=""container"">
            <ul class=""list-inline credit"">
                <li>
                    <a href=""http://github.io/odinserj/hangfire"" target=""_blank"">
                        HangFire 
                        ");


            
            #line 113 "..\..\Pages\LayoutPage.cshtml"
                   Write(FileVersionInfo.GetVersionInfo(GetType().Assembly.Location).ProductVersion);

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </a>\r\n                </li>\r\n                <li>\r\n        " +
"            ");


            
            #line 117 "..\..\Pages\LayoutPage.cshtml"
               Write(String.Format("redis://{0}:{1}/{2}", JobStorage.Configuration.RedisHost, JobStorage.Configuration.RedisPort, JobStorage.Configuration.RedisDb));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </li>\r\n                <li>Time: ");


            
            #line 119 "..\..\Pages\LayoutPage.cshtml"
                     Write(DateTime.UtcNow);

            
            #line default
            #line hidden
WriteLiteral(" UTC\r\n                </li>\r\n                <li>\r\n                    Generated " +
"in [");


            
            #line 122 "..\..\Pages\LayoutPage.cshtml"
                              Write((DateTime.UtcNow - (DateTime)Context.Items["GenerationStartedAt"]).Milliseconds);

            
            #line default
            #line hidden
WriteLiteral(" ms]\r\n                </li>\r\n            </ul>\r\n        </div>\r\n    </div>\r\n    \r" +
"\n    <script src=\"");


            
            #line 128 "..\..\Pages\LayoutPage.cshtml"
            Write(Request.LinkTo("/js/scripts.js"));

            
            #line default
            #line hidden
WriteLiteral("\"></script>\r\n</body>\r\n</html>\r\n");


        }
    }
}
#pragma warning restore 1591
