#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    using System;
    using System.Collections.Generic;
    using System.Linq;
    using System.Text;
    
    #line 2 "..\..\Pages\ProcessingJobsPage.cshtml"
    using Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class ProcessingJobsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");




            
            #line 4 "..\..\Pages\ProcessingJobsPage.cshtml"
  
    Layout = new LayoutPage { Title = "Processing Jobs" };


            
            #line default
            #line hidden
WriteLiteral("\r\n<table class=\"table\">\r\n    <thead>\r\n        <tr>\r\n            <th>Name</th>\r\n  " +
"          <th>Type</th>\r\n            <th>Args</th>\r\n            <th>Started</th>" +
"\r\n        </tr>\r\n    </thead>\r\n    <tbody>\r\n");


            
            #line 18 "..\..\Pages\ProcessingJobsPage.cshtml"
         foreach (var job in HangFireApi.ProcessingJobs())
        {

            
            #line default
            #line hidden
WriteLiteral("            <tr>\r\n                <td>");


            
            #line 21 "..\..\Pages\ProcessingJobsPage.cshtml"
               Write(job.ServerName);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td>");


            
            #line 22 "..\..\Pages\ProcessingJobsPage.cshtml"
               Write(job.Type);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                <td><code>");


            
            #line 23 "..\..\Pages\ProcessingJobsPage.cshtml"
                     Write(job.Args);

            
            #line default
            #line hidden
WriteLiteral("</code></td>\r\n                <td>");


            
            #line 24 "..\..\Pages\ProcessingJobsPage.cshtml"
               Write(job.StartedAt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n            </tr>\r\n");


            
            #line 26 "..\..\Pages\ProcessingJobsPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </tbody>\r\n</table>\r\n");


        }
    }
}
#pragma warning restore 1591
