#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HangFire.Web.Pages
{
    
    #line 2 "..\..\Pages\SucceededJobs.cshtml"
    using System;
    
    #line default
    #line hidden
    using System.Collections.Generic;
    
    #line 3 "..\..\Pages\SucceededJobs.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 4 "..\..\Pages\SucceededJobs.cshtml"
    using Pages;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class SucceededJobs : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");






            
            #line 6 "..\..\Pages\SucceededJobs.cshtml"
  
    Layout = new LayoutPage { Title = "Succeeded Jobs" };


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"alert alert-info\">\r\n    HangFire хранит последние 100 успешно выпол" +
"ненных  заданий в очереди <code>hangfire:succeeded</code>\r\n    для более простой" +
" отладки работы фоновых задач.\r\n</div>\r\n\r\n");


            
            #line 15 "..\..\Pages\SucceededJobs.cshtml"
  
    var succeededJobs = JobStorage.SucceededJobs();


            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 19 "..\..\Pages\SucceededJobs.cshtml"
 if (succeededJobs.Count == 0)
{

            
            #line default
            #line hidden
WriteLiteral("    <div class=\"alert alert-warning\">\r\n        <p>\r\n            Список завершенны" +
"х заданий пуст.\r\n    </div>\r\n");


            
            #line 25 "..\..\Pages\SucceededJobs.cshtml"
}
else
{

            
            #line default
            #line hidden
WriteLiteral(@"    <table class=""table"">
        <thead>
            <tr>
                <th>Id</th>
                <th>Type</th>
                <th>Queue</th>
                <th>Args</th>
                <th>Succeeded at</th>
            </tr>
        </thead>
        <tbody>
");


            
            #line 39 "..\..\Pages\SucceededJobs.cshtml"
             foreach (var job in succeededJobs)
            {

            
            #line default
            #line hidden
WriteLiteral("                <tr>\r\n                    <td>");


            
            #line 42 "..\..\Pages\SucceededJobs.cshtml"
                   Write(HtmlHelper.JobId(job.Key));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n\r\n");


            
            #line 44 "..\..\Pages\SucceededJobs.cshtml"
                     if (job.Value == null)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <td colspan=\"4\">The job was expired. \r\n                  " +
"      </td>\r\n");


            
            #line 48 "..\..\Pages\SucceededJobs.cshtml"
                    }
                    else
                    {    

            
            #line default
            #line hidden
WriteLiteral("                        <td>");


            
            #line 51 "..\..\Pages\SucceededJobs.cshtml"
                       Write(HtmlHelper.JobType(job.Value.Type));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("                        <td>");


            
            #line 52 "..\..\Pages\SucceededJobs.cshtml"
                       Write(HtmlHelper.QueueLabel(job.Value.Queue));

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");



WriteLiteral("                        <td>\r\n                            <code>\r\n               " +
"                 ");


            
            #line 55 "..\..\Pages\SucceededJobs.cshtml"
                           Write(String.Join(", ", job.Value.Args.Select(x => String.Format("{0}: \"{1}\"", x.Key, x.Value))));

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </code>\r\n                        </td>\r\n");



WriteLiteral("                        <td>");


            
            #line 58 "..\..\Pages\SucceededJobs.cshtml"
                       Write(job.Value.SucceededAt);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n");


            
            #line 59 "..\..\Pages\SucceededJobs.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                </tr>\r\n");


            
            #line 61 "..\..\Pages\SucceededJobs.cshtml"
            }

            
            #line default
            #line hidden
WriteLiteral("        </tbody>\r\n    </table>\r\n");


            
            #line 64 "..\..\Pages\SucceededJobs.cshtml"
}
            
            #line default
            #line hidden

        }
    }
}
#pragma warning restore 1591
