#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 5 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.Common;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 8 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 9 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    #line 10 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.States;
    
    #line default
    #line hidden
    
    #line 11 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class JobDetailsPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");













            
            #line 13 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
  
        var monitor = Storage.GetMonitoringApi();
        var job = monitor.JobDetails(JobId);

        string title = null;

        if (job != null)
        {
            title = job.Job != null ? Html.JobName(job.Job) : null;
        }

        title = title ?? Strings.Common_Job;
        Layout = new LayoutPage(title);
    

            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 30 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 33 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                           Write(title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 35 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
         if (job == null)
        {

            
            #line default
            #line hidden
WriteLiteral("            ");

WriteLiteral(" ");


            
            #line 37 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
          Write(string.Format(Strings.JobDetailsPage_JobExpired, JobId));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 38 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
        }
        else
        {
            var currentState = job.History.Count > 0 ? job.History[0] : null;
            if (currentState != null && currentState.StateName == ProcessingState.StateName)
            {
                var server = monitor.Servers().FirstOrDefault(x => x.Name == currentState.Data["ServerId"]);
                if (server == null)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"alert alert-danger\">\r\n                        ");


            
            #line 48 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                   Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobAbortedNotActive_Warning_Html, currentState.Data["ServerId"], Url.To("/servers"))));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");


            
            #line 50 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                }
                else if (server.Heartbeat.HasValue && server.Heartbeat < DateTime.UtcNow.AddMinutes(-1))
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"alert alert-warning\">\r\n                        ");


            
            #line 54 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                   Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobAbortedWithHeartbeat_Warning_Html, server.Name)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                    </div>\r\n");


            
            #line 56 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                }
            }

            if (job.ExpireAt.HasValue)
            {

            
            #line default
            #line hidden
WriteLiteral("                <div class=\"alert alert-info\">\r\n                    ");


            
            #line 62 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
               Write(Html.Raw(String.Format(Strings.JobDetailsPage_JobFinished_Warning_Html, JobHelper.ToTimestamp(job.ExpireAt.Value), job.ExpireAt)));

            
            #line default
            #line hidden
WriteLiteral("\r\n                </div>\r\n");


            
            #line 64 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
            }


            
            #line default
            #line hidden
WriteLiteral("            <div class=\"job-snippet\">\r\n                <div class=\"job-snippet-co" +
"de\">\r\n");


            
            #line 68 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                     if (job.CreatedAt.HasValue)
                    {

            
            #line default
            #line hidden
WriteLiteral("                        <div class=\"pull-right job-creation-date\">\r\n             " +
"               ");


            
            #line 71 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                       Write(Strings.JobDetailsPage_Created);

            
            #line default
            #line hidden
WriteLiteral(" ");


            
            #line 71 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                       Write(Html.RelativeTime(job.CreatedAt.Value));

            
            #line default
            #line hidden
WriteLiteral("\r\n                        </div>\r\n");


            
            #line 73 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("\r\n                    <pre><code><span class=\"comment\">// ");


            
            #line 75 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                   Write(Strings.JobDetailsPage_JobId);

            
            #line default
            #line hidden
WriteLiteral(": ");


            
            #line 75 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                  Write(Html.JobId(JobId.ToString(), false));

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n");


            
            #line 76 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
Write(JobMethodCallRenderer.Render(job.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n</code></pre>\r\n                </div>\r\n\r\n");


            
            #line 80 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                 if (job.Properties.Count > 0)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"job-snippet-properties\">\r\n                       " +
" <dl>\r\n");


            
            #line 84 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                             foreach (var property in job.Properties.Where(x => x.Key != "Continuations"))
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <dt>");


            
            #line 86 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(property.Key);

            
            #line default
            #line hidden
WriteLiteral("</dt>\r\n");



WriteLiteral("                                <dd><pre><code>");


            
            #line 87 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                          Write(property.Value);

            
            #line default
            #line hidden
WriteLiteral("</code></pre></dd>\r\n");


            
            #line 88 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </dl>\r\n                    </div>\r\n");


            
            #line 91 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("            </div>\r\n");


            
            #line 93 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"

            List<Continuation> continuations;

            using (var connection = Storage.GetConnection())
            {
                continuations = JobHelper.FromJson<List<Continuation>>(connection.GetJobParameter(
                    JobId, "Continuations")) ?? new List<Continuation>();
            }

            if (continuations.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>Continuations</h3>\r\n");



WriteLiteral(@"                <table class=""table"">
                    <thead>
                    <tr>
                        <th class=""min-width"">Id</th>
                        <th class=""min-width"">Condition</th>
                        <th class=""min-width"">State</th>
                        <th>Job</th>
                        <th class=""align-right"">Created</th>
                    </tr>
                    </thead>
                    <tbody>
");


            
            #line 116 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                     foreach (var continuation in continuations)
                    {
                        JobData jobData;

                        using (var connection = Storage.GetConnection())
                        {
                            jobData = connection.GetJobData(continuation.JobId);
                        }


            
            #line default
            #line hidden
WriteLiteral("                        <tr>\r\n");


            
            #line 126 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                             if (jobData == null)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td colspan=\"5\"><em>Job \"");


            
            #line 128 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                    Write(continuation.JobId);

            
            #line default
            #line hidden
WriteLiteral("\" has already expired.</em></td>\r\n");


            
            #line 129 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <td class=\"min-width\">\r\n                         " +
"           ");


            
            #line 133 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(Html.JobIdLink(continuation.JobId));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n");



WriteLiteral("                                <td class=\"min-width\">\r\n                         " +
"           <code>");


            
            #line 136 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                     Write(continuation.Options.ToString("G"));

            
            #line default
            #line hidden
WriteLiteral("</code>\r\n                                </td>\r\n");



WriteLiteral("                                <td class=\"min-width\">\r\n                         " +
"           ");


            
            #line 139 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(Html.StateLabel(jobData.State));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n");



WriteLiteral("                                <td>\r\n                                    ");


            
            #line 142 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(Html.JobNameLink(continuation.JobId, jobData.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n");



WriteLiteral("                                <td class=\"align-right\">\r\n                       " +
"             ");


            
            #line 145 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(Html.RelativeTime(jobData.CreatedAt));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </td>\r\n");


            
            #line 147 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </tr>\r\n");


            
            #line 149 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                    }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n");


            
            #line 152 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
            }

            if (job.History.Count > 0)
            {

            
            #line default
            #line hidden
WriteLiteral("                <h3>\r\n                    <span class=\"job-snippet-buttons pull-r" +
"ight\">\r\n                        <button class=\"btn btn-sm btn-default\" data-ajax" +
"=\"");


            
            #line 158 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                     Write(Url.To("/jobs/actions/requeue/" + JobId));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 158 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                   Write(Strings.Common_Enqueueing);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 158 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                                               Write(Strings.JobDetailsPage_Requeue);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                        <button class=\"btn btn-sm btn-death\" data-ajax" +
"=\"");


            
            #line 159 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                   Write(Url.To("/jobs/actions/delete/" + JobId));

            
            #line default
            #line hidden
WriteLiteral("\" data-loading-text=\"");


            
            #line 159 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                Write(Strings.Common_Deleting);

            
            #line default
            #line hidden
WriteLiteral("\" data-confirm=\"");


            
            #line 159 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                                                        Write(Strings.JobDetailsPage_DeleteConfirm);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 159 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                                                                                               Write(Strings.Common_Delete);

            
            #line default
            #line hidden
WriteLiteral("</button>\r\n                    </span>\r\n\r\n                    ");


            
            #line 162 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
               Write(Strings.JobDetailsPage_State);

            
            #line default
            #line hidden
WriteLiteral("\r\n                </h3>\r\n");


            
            #line 164 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"

                var index = 0;

                DateTime[] entriesCreationTime = job.History.Select(x => x.CreatedAt).ToArray();
                var nextEntry = 1;

                foreach (var entry in job.History)
                {
                    var accentColor = JobHistoryRenderer.GetForegroundStateColor(entry.StateName);
                    var backgroundColor = JobHistoryRenderer.GetBackgroundStateColor(entry.StateName);


            
            #line default
            #line hidden
WriteLiteral("                    <div class=\"state-card\" style=\"");


            
            #line 175 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                               Write(index == 0 ? $"border-color: {accentColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                        <h4 class=\"state-card-title\">\r\n                      " +
"      <small class=\"pull-right text-muted\">\r\n");


            
            #line 178 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                  
                                    var duration = Html.ToHumanDuration(entry.CreatedAt - (nextEntry < entriesCreationTime.Length ? entriesCreationTime[nextEntry] : job.CreatedAt));
                                    nextEntry++;
                                

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 183 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                 if (index == 0)
                                {
                                    
            
            #line default
            #line hidden
            
            #line 185 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                               Write(Html.Raw($"{Html.RelativeTime(entry.CreatedAt)} (<span data-moment-title=\"{JobHelper.ToTimestamp(entry.CreatedAt)}\">{duration}</span>)"));

            
            #line default
            #line hidden
            
            #line 185 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                                                                                                               
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    ");

WriteLiteral(" ");


            
            #line 189 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                  Write(duration);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 190 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </small>\r\n\r\n                            <span style=\"" +
"");


            
            #line 193 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                     Write(index == 0 ? $"color: {accentColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 193 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                                                    Write(entry.StateName);

            
            #line default
            #line hidden
WriteLiteral("</span>\r\n                        </h4>\r\n\r\n\r\n");


            
            #line 197 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                         if (!String.IsNullOrWhiteSpace(entry.Reason))
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <p class=\"state-card-text text-muted\">");


            
            #line 199 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                             Write(entry.Reason);

            
            #line default
            #line hidden
WriteLiteral("</p>\r\n");


            
            #line 200 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 202 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                          
                            var rendered = Html.RenderHistory(entry.StateName, entry.Data);
                        

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 206 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                         if (rendered != null)
                        {

            
            #line default
            #line hidden
WriteLiteral("                            <div class=\"job-history-body\" style=\"");


            
            #line 208 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                                                             Write(index == 0 ? $"background-color: {backgroundColor}" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 209 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                           Write(rendered);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </div>\r\n");


            
            #line 211 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </div>\r\n");


            
            #line 213 "..\..\Dashboard\Pages\JobDetailsPage.cshtml"

                    index++;
                }
            }
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
