#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    using System;
    using System.Collections.Generic;
    
    #line 2 "..\..\Dashboard\Pages\QueuesPage.cshtml"
    using System.Linq;
    
    #line default
    #line hidden
    using System.Text;
    
    #line 3 "..\..\Dashboard\Pages\QueuesPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 4 "..\..\Dashboard\Pages\QueuesPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\QueuesPage.cshtml"
    using Hangfire.Dashboard.Resources;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class QueuesPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");







            
            #line 7 "..\..\Dashboard\Pages\QueuesPage.cshtml"
  
    Layout = new LayoutPage(Strings.QueuesPage_Title);

    var monitor = Storage.GetMonitoringApi();
    var queues = monitor.Queues();


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-3\">\r\n        ");


            
            #line 16 "..\..\Dashboard\Pages\QueuesPage.cshtml"
   Write(Html.JobsSidebar());

            
            #line default
            #line hidden
WriteLiteral("\r\n    </div>\r\n    <div class=\"col-md-9\">\r\n        <h1 class=\"page-header\">");


            
            #line 19 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                           Write(Strings.QueuesPage_Title);

            
            #line default
            #line hidden
WriteLiteral("</h1>\r\n\r\n");


            
            #line 21 "..\..\Dashboard\Pages\QueuesPage.cshtml"
         if (queues.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-warning\">\r\n                ");


            
            #line 24 "..\..\Dashboard\Pages\QueuesPage.cshtml"
           Write(Strings.QueuesPage_NoQueues);

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 26 "..\..\Dashboard\Pages\QueuesPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <table class=\"table table-striped\">\r\n                <thead>\r\n       " +
"         <tr>\r\n                    <th>");


            
            #line 32 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                   Write(Strings.QueuesPage_Table_Queue);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th>");


            
            #line 33 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                   Write(Strings.QueuesPage_Table_Length);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th>");


            
            #line 34 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                   Write(Strings.Common_Fetched);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                    <th>");


            
            #line 35 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                   Write(Strings.QueuesPage_Table_NextsJobs);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                </tr>\r\n                </thead>\r\n                <tbody>\r\n" +
"");


            
            #line 39 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                 foreach (var queue in queues)
                {

            
            #line default
            #line hidden
WriteLiteral("                    <tr>\r\n                        <td>\r\n                         " +
"   <a class=\"label-queue\" href=\"");


            
            #line 43 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                    Write(Url.Queue(queue.Name));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                ");


            
            #line 44 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                           Write(queue.Name);

            
            #line default
            #line hidden
WriteLiteral("\r\n                            </a>\r\n                        </td>\r\n              " +
"          <td>");


            
            #line 47 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                       Write(queue.Length);

            
            #line default
            #line hidden
WriteLiteral("</td>\r\n                        <td>\r\n");


            
            #line 49 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                             if (queue.Fetched.HasValue)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <a href=\"");


            
            #line 51 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                    Write(Url.To("/jobs/enqueued/fetched/" + queue.Name));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                    ");


            
            #line 52 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                               Write(queue.Fetched);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </a>\r\n");


            
            #line 54 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <em>");


            
            #line 57 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                               Write(Strings.Common_NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n");


            
            #line 58 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                        <td>\r\n");


            
            #line 61 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                             if (queue.FirstJobs.Count == 0)
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <em>\r\n                                    ");


            
            #line 64 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                               Write(Strings.QueuesPage_NoJobs);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                </em>\r\n");


            
            #line 66 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                            }
                            else
                            {

            
            #line default
            #line hidden
WriteLiteral("                                <table class=\"table table-condensed table-bordere" +
"d table-inner\">\r\n                                    <thead>\r\n                  " +
"                  <tr>\r\n                                        <th class=\"min-w" +
"idth\">");


            
            #line 72 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                         Write(Strings.Common_Id);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                        <th class=\"min-width\">");


            
            #line 73 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                         Write(Strings.Common_State);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                        <th>");


            
            #line 74 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                       Write(Strings.Common_Job);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                        <th class=\"align-right min-width\">" +
"");


            
            #line 75 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                                     Write(Strings.Common_Enqueued);

            
            #line default
            #line hidden
WriteLiteral("</th>\r\n                                    </tr>\r\n                               " +
"     </thead>\r\n                                    <tbody>\r\n");


            
            #line 79 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                     foreach (var job in queue.FirstJobs.Where(j => j.Value != null))
                                    {

            
            #line default
            #line hidden
WriteLiteral("                                        <tr class=\"");


            
            #line 81 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                               Write(!job.Value.InEnqueuedState ? "obsolete-data" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                            <td class=\"min-width\">\r\n         " +
"                                       ");


            
            #line 83 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                           Write(Html.JobIdLink(job.Key));

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 84 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                 if (!job.Value.InEnqueuedState)
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <span title=\"");


            
            #line 86 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                            Write(Strings.Common_JobStateChanged_Text);

            
            #line default
            #line hidden
WriteLiteral("\" class=\"glyphicon glyphicon-question-sign\"></span>\r\n");


            
            #line 87 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </td>\r\n                              " +
"              <td class=\"min-width\">\r\n                                          " +
"      ");


            
            #line 90 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                           Write(Html.StateLabel(job.Value.State));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </td>\r\n                            " +
"                <td>\r\n                                                ");


            
            #line 93 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                           Write(Html.JobNameLink(job.Key, job.Value.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </td>\r\n                            " +
"                <td class=\"align-right min-width\">\r\n");


            
            #line 96 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                 if (job.Value.EnqueuedAt.HasValue)
                                                {
                                                    
            
            #line default
            #line hidden
            
            #line 98 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                               Write(Html.RelativeTime(job.Value.EnqueuedAt.Value));

            
            #line default
            #line hidden
            
            #line 98 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                                                                  
                                                }
                                                else
                                                {

            
            #line default
            #line hidden
WriteLiteral("                                                    <em>");


            
            #line 102 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                   Write(Strings.Common_NotAvailable);

            
            #line default
            #line hidden
WriteLiteral("</em>\r\n");


            
            #line 103 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                                }

            
            #line default
            #line hidden
WriteLiteral("                                            </td>\r\n                              " +
"          </tr>\r\n");


            
            #line 106 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                                    }

            
            #line default
            #line hidden
WriteLiteral("                                    </tbody>\r\n                                </t" +
"able>\r\n");


            
            #line 109 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                            }

            
            #line default
            #line hidden
WriteLiteral("                        </td>\r\n                    </tr>\r\n");


            
            #line 112 "..\..\Dashboard\Pages\QueuesPage.cshtml"
                }

            
            #line default
            #line hidden
WriteLiteral("                </tbody>\r\n            </table>\r\n");


            
            #line 115 "..\..\Dashboard\Pages\QueuesPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
