#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Hangfire.Dashboard.Pages
{
    
    #line 2 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using System;
    
    #line default
    #line hidden
    
    #line 3 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using System.Collections.Generic;
    
    #line default
    #line hidden
    using System.Linq;
    using System.Text;
    
    #line 4 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using Hangfire.Common;
    
    #line default
    #line hidden
    
    #line 5 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using Hangfire.Dashboard;
    
    #line default
    #line hidden
    
    #line 6 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using Hangfire.Dashboard.Pages;
    
    #line default
    #line hidden
    
    #line 7 "..\..\Dashboard\Pages\RetriesPage.cshtml"
    using Hangfire.Storage;
    
    #line default
    #line hidden
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("RazorGenerator", "2.0.0.0")]
    internal partial class RetriesPage : RazorPage
    {
#line hidden

        public override void Execute()
        {


WriteLiteral("\r\n");









            
            #line 9 "..\..\Dashboard\Pages\RetriesPage.cshtml"
  
    Layout = new LayoutPage("Retries");
    
    int from, perPage;

    int.TryParse(Query("from"), out from);
    int.TryParse(Query("count"), out perPage);

    Pager pager;
    List<string> jobIds;

    using (var connection = Storage.GetConnection())
    {
        var storageConnection = connection as JobStorageConnection;
        
        pager = new Pager(from, perPage, storageConnection.GetSetCount("retries"));
        jobIds = storageConnection.GetRangeFromSet("retries", pager.FromRecord, pager.FromRecord + pager.RecordsPerPage - 1);
    }


            
            #line default
            #line hidden
WriteLiteral("\r\n<div class=\"row\">\r\n    <div class=\"col-md-12\">\r\n        <h1 class=\"page-header\"" +
">Retries</h1>\r\n");


            
            #line 32 "..\..\Dashboard\Pages\RetriesPage.cshtml"
         if (jobIds.Count == 0)
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"alert alert-info\">\r\n                All is OK – you have " +
"no retries.\r\n            </div>\r\n");


            
            #line 37 "..\..\Dashboard\Pages\RetriesPage.cshtml"
        }
        else
        {

            
            #line default
            #line hidden
WriteLiteral("            <div class=\"js-jobs-list\">\r\n                <div class=\"btn-toolbar b" +
"tn-toolbar-top\">\r\n                    <button class=\"js-jobs-list-command btn bt" +
"n-sm btn-primary\"\r\n                            data-url=\"");


            
            #line 43 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                 Write(LinkTo("/jobs/scheduled/enqueue"));

            
            #line default
            #line hidden
WriteLiteral(@"""
                            data-loading-text=""Enqueueing..."">
                        <span class=""glyphicon glyphicon-repeat""></span>
                        Enqueue jobs
                    </button>

                    <button class=""js-jobs-list-command btn btn-sm btn-default""
                            data-url=""");


            
            #line 50 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                 Write(LinkTo("/jobs/scheduled/delete"));

            
            #line default
            #line hidden
WriteLiteral(@"""
                            data-loading-text=""Deleting...""
                            data-confirm=""Do you really want to DELETE ALL selected jobs?"">
                        <span class=""glyphicon glyphicon-remove""></span>
                        Delete selected
                    </button>

                    ");


            
            #line 57 "..\..\Dashboard\Pages\RetriesPage.cshtml"
               Write(RenderPartial(new PerPageSelector(pager)));

            
            #line default
            #line hidden
WriteLiteral(@"
                </div>

                <table class=""table table-hover"">
                    <thead>
                        <tr>
                            <th class=""min-width"">
                                <input type=""checkbox"" class=""js-jobs-list-select-all"" />
                            </th>
                            <th class=""min-width"">Id</th>
                            <th class=""min-width"">State</th>
                            <th>Job</th>
                            <th>Reason</th>
                            <th class=""align-right"">Created</th>
                        </tr>
                    </thead>
                    <tbody>
");


            
            #line 74 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                         foreach (var jobId in jobIds)
                        {
                            JobData jobData;
                            StateData stateData;

                            using (var connection = Storage.GetConnection())
                            {
                                jobData = connection.GetJobData(jobId);
                                stateData = connection.GetStateData(jobId);
                            }


            
            #line default
            #line hidden
WriteLiteral("                            <tr class=\"js-jobs-list-row ");


            
            #line 85 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                    Write(jobData != null ? "hover" : null);

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                <td>\r\n                                    <in" +
"put type=\"checkbox\" class=\"js-jobs-list-checkbox\" name=\"jobs[]\" value=\"");


            
            #line 87 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                                                                         Write(jobId);

            
            #line default
            #line hidden
WriteLiteral("\" />\r\n                                </td>\r\n                                <td " +
"class=\"min-width\">\r\n                                    <a href=\"");


            
            #line 90 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                        Write(LinkTo("/jobs/" + jobId));

            
            #line default
            #line hidden
WriteLiteral("\">");


            
            #line 90 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                                   Write(HtmlHelper.JobId(jobId));

            
            #line default
            #line hidden
WriteLiteral("</a>\r\n                                </td>\r\n");


            
            #line 92 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                 if (jobData == null)
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td colspan=\"4\"><em>Job expired.</em></td>\r\n");


            
            #line 95 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                }
                                else
                                {

            
            #line default
            #line hidden
WriteLiteral("                                    <td class=\"min-width\">\r\n");


            
            #line 99 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                         if (!String.IsNullOrWhiteSpace(jobData.State))
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <span class=\"label label-default\" sty" +
"le=\"");


            
            #line 101 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                                                 Write(String.Format("background-color: {0};", JobHistoryRenderer.GetForegroundStateColor(jobData.State)));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                                ");


            
            #line 102 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                           Write(jobData.State);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                            </span>\r\n");


            
            #line 104 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                        }
                                        else
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            <em>No state</em>\r\n");


            
            #line 108 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n");



WriteLiteral("                                    <td>\r\n                                       " +
" <a class=\"job-method\" href=\"");


            
            #line 111 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                               Write(LinkTo("/jobs/" + jobId));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                            ");


            
            #line 112 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                       Write(HtmlHelper.DisplayJob(jobData.Job));

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </a>\r\n                                 " +
"   </td>\r\n");



WriteLiteral("                                    <td>\r\n");


            
            #line 116 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                         if (stateData != null)
                                        {

            
            #line default
            #line hidden
WriteLiteral("                                            ");

WriteLiteral(" ");


            
            #line 118 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                          Write(stateData.Reason);

            
            #line default
            #line hidden
WriteLiteral("\r\n");


            
            #line 119 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                        }

            
            #line default
            #line hidden
WriteLiteral("                                    </td>\r\n");



WriteLiteral("                                    <td class=\"align-right\">\r\n                   " +
"                     <span data-moment=\"");


            
            #line 122 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                                      Write(JobHelper.ToTimestamp(jobData.CreatedAt));

            
            #line default
            #line hidden
WriteLiteral("\">\r\n                                            ");


            
            #line 123 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                       Write(jobData.CreatedAt);

            
            #line default
            #line hidden
WriteLiteral("\r\n                                        </span>\r\n                              " +
"      </td>\r\n");


            
            #line 126 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                                }

            
            #line default
            #line hidden
WriteLiteral("                            </tr>\r\n");


            
            #line 128 "..\..\Dashboard\Pages\RetriesPage.cshtml"
                        }

            
            #line default
            #line hidden
WriteLiteral("                    </tbody>\r\n                </table>\r\n                ");


            
            #line 131 "..\..\Dashboard\Pages\RetriesPage.cshtml"
           Write(RenderPartial(new Paginator(pager)));

            
            #line default
            #line hidden
WriteLiteral("\r\n            </div>\r\n");


            
            #line 133 "..\..\Dashboard\Pages\RetriesPage.cshtml"
        }

            
            #line default
            #line hidden
WriteLiteral("    </div>\r\n</div>");


        }
    }
}
#pragma warning restore 1591
